### ISSUE TITLE
Gibt es dort eine aktuellere Version von? Sieht so unfertig aus.

### ISSUE THREAD

**Issue by ysl3000** [tr7zw/PIS_Hausuebung2#1]
Hier mal zwei Projekte zur Inspiration.

https://github.com/ysl3000/SocketChat/tree/Baseversion
https://github.com/ysl3000/RMI/tree/master/RMIServer/src/de/thm/iem/yannicklamprecht/server
Die RMI Version hat Commands. An einigen Stellen müsste sie noch verbessert werden.

**Comment by yannickdreherstudium** [comment]
Ist ein Projekt mit festen Vorgaben und ist nun fertig
